import { useState, useEffect, useRef } from 'react';
import { JobResults } from '../services/api';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  results: JobResults;
  datasetFilename?: string;
}

type ExportFormat = 'json' | 'python' | 'go' | 'cpp';

export const ExportModal = ({ isOpen, onClose, results, datasetFilename }: ExportModalProps) => {
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>('json');
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const modalRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  // Close on Escape key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleEscape);
    return () => window.removeEventListener('keydown', handleEscape);
  }, [isOpen, onClose]);

  // Prevent body scroll when modal is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      // Focus trap
      modalRef.current?.focus();
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  // Scroll to top when format changes
  useEffect(() => {
    if (contentRef.current) {
      contentRef.current.scrollTop = 0;
    }
  }, [selectedFormat]);

  if (!isOpen) return null;

  const generateJSONExport = (): string => {
    const exportData = {
      job_id: results.job_id,
      dataset: datasetFilename || 'dataset.csv',
      best_model: {
        name: results.best_model.name,
        hyperparameters: results.best_model.hyperparameters,
        selected_features: results.best_model.selected_features,
      },
      metrics: results.metrics,
      feature_importance: results.feature_importance,
      data_splits: results.data_splits,
      training_history: results.training_history,
    };
    return JSON.stringify(exportData, null, 2);
  };

  const generatePythonCode = (): string => {
    const modelName = results.best_model.name.toLowerCase();
    const hyperparams = results.best_model.hyperparameters;
    const features = results.best_model.selected_features;
    
    let modelClass = '';
    let importPath = '';
    
    if (modelName === 'random_forest') {
      modelClass = 'RandomForestClassifier';
      importPath = 'from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor';
    } else if (modelName === 'xgboost') {
      modelClass = 'XGBClassifier';
      importPath = 'import xgboost as xgb\nfrom xgboost import XGBClassifier, XGBRegressor';
    } else if (modelName === 'svm') {
      modelClass = 'SVC';
      importPath = 'from sklearn.svm import SVC, SVR';
    } else if (modelName === 'logistic_regression') {
      modelClass = 'LogisticRegression';
      importPath = 'from sklearn.linear_model import LogisticRegression, Ridge';
    } else {
      modelClass = 'RandomForestClassifier';
      importPath = 'from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor';
    }
    
    let code = `# Model Export - Python\n`;
    code += `# Generated by METIS\n`;
    code += `# Dataset: ${datasetFilename || 'dataset.csv'}\n`;
    code += `# Model: ${results.best_model.name}\n\n`;
    code += `import pandas as pd\n`;
    code += `import numpy as np\n`;
    code += `${importPath}\n\n`;
    code += `# Load dataset\n`;
    code += `df = pd.read_csv('${datasetFilename || 'dataset.csv'}')\n\n`;
    code += `# Prepare features (using selected features from AutoML)\n`;
    code += `selected_features = ${JSON.stringify(features)}\n`;
    code += `X = df[selected_features]\n`;
    code += `# Adjust target column name as needed (common names: 'target', 'label', 'y', 'class')\n`;
    code += `y = df['target']  # TODO: Replace 'target' with your actual target column name\n\n`;
    code += `# Initialize model with optimized hyperparameters\n`;
    code += `hyperparameters = ${JSON.stringify(hyperparams, null, 2)}\n`;
    code += `# Note: Use ${modelClass} for classification, or corresponding Regressor for regression\n`;
    code += `model = ${modelClass}(**hyperparameters, random_state=42)\n\n`;
    code += `# Train the model\n`;
    code += `model.fit(X, y)\n\n`;
    code += `# Make predictions\n`;
    code += `predictions = model.predict(X)\n`;
    code += `print(f"Model trained with {len(selected_features)} features")\n`;
    code += `print(f"Training score: ${results.metrics.train_score.toFixed(4)}")\n`;
    code += `print(f"Validation score: ${results.metrics.validation_score.toFixed(4)}")\n`;
    return code;
  };

  const generateGoCode = (): string => {
    const modelName = results.best_model.name;
    const hyperparams = results.best_model.hyperparameters;
    const features = results.best_model.selected_features;
    
    let code = `// Model Export - Go\n`;
    code += `// Generated by METIS\n`;
    code += `// Dataset: ${datasetFilename || 'dataset.csv'}\n\n`;
    code += `package main\n\n`;
    code += `import (\n`;
    code += `\t"encoding/csv"\n`;
    code += `\t"fmt"\n`;
    code += `\t"log"\n`;
    code += `\t"os"\n`;
    code += `)\n\n`;
    code += `// Hyperparameters from AutoML optimization\n`;
    code += `var hyperparameters = map[string]interface{}{\n`;
    Object.entries(hyperparams).forEach(([key, value]) => {
      code += `\t"${key}": ${JSON.stringify(value)},\n`;
    });
    code += `}\n\n`;
    code += `// Selected features from AutoML\n`;
    code += `var selectedFeatures = []string{\n`;
    features.forEach(feature => {
      code += `\t"${feature}",\n`;
    });
    code += `}\n\n`;
    code += `func main() {\n`;
    code += `\t// Load dataset\n`;
    code += `\tfile, err := os.Open("${datasetFilename || 'dataset.csv'}")\n`;
    code += `\tif err != nil {\n`;
    code += `\t\tlog.Fatal(err)\n`;
    code += `\t}\n`;
    code += `\tdefer file.Close()\n\n`;
    code += `\treader := csv.NewReader(file)\n`;
    code += `\trecords, err := reader.ReadAll()\n`;
    code += `\tif err != nil {\n`;
    code += `\t\tlog.Fatal(err)\n`;
    code += `\t}\n\n`;
    code += `\tfmt.Printf("Loaded dataset with %d features\\n", len(selectedFeatures))\n`;
    code += `\tfmt.Printf("Model: %s\\n", "${modelName}")\n`;
    code += `\tfmt.Printf("Hyperparameters: %+v\\n", hyperparameters)\n`;
    code += `\t// TODO: Implement model training using a Go ML library\n`;
    code += `\t// Recommended: goml, gorgonia, or gonum\n`;
    code += `}\n`;
    return code;
  };

  const generateCppCode = (): string => {
    const modelName = results.best_model.name;
    const hyperparams = results.best_model.hyperparameters;
    const features = results.best_model.selected_features;
    
    let code = `// Model Export - C++\n`;
    code += `// Generated by METIS\n`;
    code += `// Dataset: ${datasetFilename || 'dataset.csv'}\n\n`;
    code += `#include <iostream>\n`;
    code += `#include <vector>\n`;
    code += `#include <string>\n`;
    code += `#include <map>\n\n`;
    code += `// Hyperparameters from AutoML optimization\n`;
    code += `std::map<std::string, double> hyperparameters = {\n`;
    Object.entries(hyperparams).forEach(([key, value]) => {
      const numValue = typeof value === 'number' ? value : 0;
      code += `\t{"${key}", ${numValue}},\n`;
    });
    code += `};\n\n`;
    code += `// Selected features from AutoML\n`;
    code += `std::vector<std::string> selectedFeatures = {\n`;
    features.forEach(feature => {
      code += `\t"${feature}",\n`;
    });
    code += `};\n\n`;
    code += `int main() {\n`;
    code += `\tstd::cout << "Loading dataset: ${datasetFilename || 'dataset.csv'}" << std::endl;\n`;
    code += `\tstd::cout << "Model: ${modelName}" << std::endl;\n`;
    code += `\tstd::cout << "Features: " << selectedFeatures.size() << std::endl;\n`;
    code += `\t\n`;
    code += `\t// TODO: Implement CSV loading and model training\n`;
    code += `\t// Recommended libraries:\n`;
    code += `\t// - CSV: csv-parser or fast-cpp-csv-parser\n`;
    code += `\t// - ML: mlpack, dlib, or OpenCV\n`;
    code += `\t\n`;
    code += `\treturn 0;\n`;
    code += `}\n`;
    return code;
  };

  const getExportContent = (): string => {
    switch (selectedFormat) {
      case 'json':
        return generateJSONExport();
      case 'python':
        return generatePythonCode();
      case 'go':
        return generateGoCode();
      case 'cpp':
        return generateCppCode();
      default:
        return '';
    }
  };

  const handleCopy = async () => {
    try {
      const content = getExportContent();
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownload = () => {
    setDownloading(true);
    const content = getExportContent();
    const extension = selectedFormat === 'json' ? 'json' : selectedFormat === 'python' ? 'py' : selectedFormat === 'go' ? 'go' : 'cpp';
    const filename = `automl_export_${results.job_id.slice(0, 8)}.${extension}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setTimeout(() => setDownloading(false), 500);
  };

  const formats: { value: ExportFormat; label: string; description: string; icon: JSX.Element }[] = [
    { 
      value: 'json', 
      label: 'JSON', 
      description: 'Structured data format',
      icon: (
        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
        </svg>
      )
    },
    { 
      value: 'python', 
      label: 'Python', 
      description: 'scikit-learn compatible',
      icon: (
        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
        </svg>
      )
    },
    { 
      value: 'go', 
      label: 'Go', 
      description: 'Go implementation',
      icon: (
        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
        </svg>
      )
    },
    { 
      value: 'cpp', 
      label: 'C++', 
      description: 'C++ implementation',
      icon: (
        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
        </svg>
      )
    },
  ];

  const formatColors: Record<ExportFormat, { bg: string; border: string; text: string; icon: string }> = {
    json: {
      bg: 'bg-blue-500/10',
      border: 'border-blue-500/30',
      text: 'text-blue-400',
      icon: 'text-blue-500'
    },
    python: {
      bg: 'bg-yellow-500/10',
      border: 'border-yellow-500/30',
      text: 'text-yellow-400',
      icon: 'text-yellow-500'
    },
    go: {
      bg: 'bg-cyan-500/10',
      border: 'border-cyan-500/30',
      text: 'text-cyan-400',
      icon: 'text-cyan-500'
    },
    cpp: {
      bg: 'bg-purple-500/10',
      border: 'border-purple-500/30',
      text: 'text-purple-400',
      icon: 'text-purple-500'
    },
  };

  const currentColor = formatColors[selectedFormat];

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/70 backdrop-blur-sm animate-fade-in"
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          onClose();
        }
      }}
      role="dialog"
      aria-modal="true"
      aria-labelledby="export-modal-title"
    >
      <div 
        ref={modalRef}
        tabIndex={-1}
        className="bg-[var(--bg-card)] rounded-2xl shadow-2xl border border-[var(--border)] w-full max-w-6xl max-h-[90vh] flex flex-col overflow-hidden animate-scale-in"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header - Fixed */}
        <div className="flex items-center justify-between px-6 py-5 border-b border-[var(--border)] bg-gradient-to-r from-[var(--bg-card)] via-[var(--bg-elevated)]/50 to-[var(--bg-card)] shrink-0">
          <div className="flex items-center gap-4">
            <div className={`w-12 h-12 rounded-xl ${currentColor.bg} ${currentColor.border} border-2 flex items-center justify-center ${currentColor.icon} transition-colors duration-200`}>
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div>
              <h2 id="export-modal-title" className="text-2xl font-bold text-[var(--text-primary)] tracking-tight">
                Export Model Configuration
              </h2>
              <p className="text-sm text-[var(--text-muted)] mt-1">
                Download or copy your optimized model in your preferred format
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-all p-2 hover:bg-[var(--bg-elevated)] rounded-lg active:scale-95 focus:outline-none focus:ring-2 focus:ring-[var(--primary)] focus:ring-offset-2 focus:ring-offset-[var(--bg-card)]"
            aria-label="Close modal"
          >
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content Area - Scrollable */}
        <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
          {/* Format Selection - Sticky */}
          <div className="px-6 pt-6 pb-4 border-b border-[var(--border)] bg-[var(--bg-card)] shrink-0">
            <div className="mb-4">
              <label className="text-xs font-semibold text-[var(--text-muted)] uppercase tracking-wider mb-1 block">
                Export Format
              </label>
              <p className="text-xs text-[var(--text-muted)]">Choose the format that best fits your workflow</p>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {formats.map((format) => {
                const isSelected = selectedFormat === format.value;
                const colors = formatColors[format.value];
                return (
                  <button
                    key={format.value}
                    onClick={() => setSelectedFormat(format.value)}
                    className={`relative px-4 py-4 rounded-xl transition-all duration-200 border-2 text-left group ${
                      isSelected
                        ? `${colors.bg} ${colors.border} ${colors.text} shadow-lg scale-[1.02]`
                        : 'bg-[var(--bg-elevated)] border-[var(--border)] text-[var(--text-secondary)] hover:bg-[var(--bg-card)] hover:border-[var(--border)]/80 hover:scale-[1.01]'
                    } focus:outline-none focus:ring-2 focus:ring-[var(--primary)] focus:ring-offset-2 focus:ring-offset-[var(--bg-card)]`}
                  >
                    <div className="flex flex-col gap-2">
                      <div className={`flex items-center gap-2 ${isSelected ? colors.icon : 'text-[var(--text-muted)]'}`}>
                        {format.icon}
                        <span className="font-semibold text-sm">{format.label}</span>
                      </div>
                      <p className={`text-xs ${isSelected ? 'opacity-80' : 'text-[var(--text-muted)]'}`}>
                        {format.description}
                      </p>
                    </div>
                    {isSelected && (
                      <div className={`absolute -top-2 -right-2 w-4 h-4 ${colors.bg} ${colors.border} border-2 rounded-full flex items-center justify-center`}>
                        <div className={`w-2 h-2 ${colors.icon.replace('text-', 'bg-')} rounded-full`}></div>
                      </div>
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Code Preview - Scrollable */}
          <div className="flex-1 min-h-0 flex flex-col px-6 py-6 overflow-hidden">
            <div className="flex items-center justify-between mb-4 shrink-0">
              <div>
                <label className="text-xs font-semibold text-[var(--text-muted)] uppercase tracking-wider block mb-1">
                  Code Preview
                </label>
                <p className="text-xs text-[var(--text-muted)]">
                  {selectedFormat === 'json' ? 'JSON configuration' : `${formats.find(f => f.value === selectedFormat)?.label} code`}
                </p>
              </div>
              <div className="flex items-center gap-2 px-3 py-1.5 bg-[var(--bg-elevated)] rounded-lg border border-[var(--border)]">
                <svg className="w-3.5 h-3.5 text-[var(--text-muted)]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                </svg>
                <span className="text-xs text-[var(--text-muted)] font-medium">Read-only</span>
              </div>
            </div>
            <div 
              ref={contentRef}
              className="flex-1 bg-[var(--bg-elevated)] rounded-xl border border-[var(--border)] overflow-auto custom-scrollbar shadow-inner"
            >
              <div className="p-6">
                <pre className="text-xs text-[var(--text-secondary)] font-mono whitespace-pre leading-relaxed">
                  <code>{getExportContent()}</code>
                </pre>
              </div>
            </div>
          </div>
        </div>

        {/* Footer - Fixed */}
        <div className="flex items-center justify-between gap-4 px-6 py-5 border-t border-[var(--border)] bg-[var(--bg-elevated)]/30 backdrop-blur-sm shrink-0">
          <div className="flex items-center gap-3 text-xs text-[var(--text-muted)]">
            <div className="flex items-center gap-2 px-3 py-1.5 bg-[var(--bg-card)] rounded-lg border border-[var(--border)]">
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
              </svg>
              <span className="font-mono font-medium">{results.job_id.slice(0, 8)}</span>
            </div>
            <span className="text-[var(--text-muted)]">•</span>
            <span>{datasetFilename || 'dataset.csv'}</span>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={onClose}
              className="px-5 py-2.5 text-sm font-medium text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors rounded-lg hover:bg-[var(--bg-elevated)] focus:outline-none focus:ring-2 focus:ring-[var(--primary)] focus:ring-offset-2 focus:ring-offset-[var(--bg-elevated)]"
            >
              Cancel
            </button>
            <button
              onClick={handleCopy}
              className={`px-5 py-2.5 text-sm font-medium rounded-lg transition-all flex items-center gap-2 border focus:outline-none focus:ring-2 focus:ring-[var(--primary)] focus:ring-offset-2 focus:ring-offset-[var(--bg-elevated)] ${
                copied
                  ? 'bg-[var(--success)]/20 text-[var(--success)] border-[var(--success)]/30'
                  : 'bg-[var(--bg-elevated)] text-[var(--text-primary)] hover:bg-[var(--bg-card)] border-[var(--border)] hover:border-[var(--border)]/80'
              }`}
            >
              {copied ? (
                <>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy
                </>
              )}
            </button>
            <button
              onClick={handleDownload}
              disabled={downloading}
              className={`px-6 py-2.5 text-sm font-semibold bg-gradient-to-r from-[var(--primary)] to-[var(--accent)] text-white rounded-lg hover:shadow-lg hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center gap-2 focus:outline-none focus:ring-2 focus:ring-[var(--primary)] focus:ring-offset-2 focus:ring-offset-[var(--bg-elevated)] disabled:opacity-50 disabled:cursor-not-allowed`}
            >
              {downloading ? (
                <>
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Downloading...
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Download
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
